/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingReturnRouteImport } from './routes/booking.return'
import { Route as ApiToyyibpayCallbackRouteImport } from './routes/api/toyyibpay-callback'
import { Route as ApiAdminOneOffFixRouteImport } from './routes/api/admin/one-off-fix'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingReturnRoute = BookingReturnRouteImport.update({
  id: '/booking/return',
  path: '/booking/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToyyibpayCallbackRoute = ApiToyyibpayCallbackRouteImport.update({
  id: '/api/toyyibpay-callback',
  path: '/api/toyyibpay-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOneOffFixRoute = ApiAdminOneOffFixRouteImport.update({
  id: '/api/admin/one-off-fix',
  path: '/api/admin/one-off-fix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/toyyibpay-callback': typeof ApiToyyibpayCallbackRoute
  '/booking/return': typeof BookingReturnRoute
  '/api/admin/one-off-fix': typeof ApiAdminOneOffFixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/toyyibpay-callback': typeof ApiToyyibpayCallbackRoute
  '/booking/return': typeof BookingReturnRoute
  '/api/admin/one-off-fix': typeof ApiAdminOneOffFixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/toyyibpay-callback': typeof ApiToyyibpayCallbackRoute
  '/booking/return': typeof BookingReturnRoute
  '/api/admin/one-off-fix': typeof ApiAdminOneOffFixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/toyyibpay-callback'
    | '/booking/return'
    | '/api/admin/one-off-fix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/toyyibpay-callback'
    | '/booking/return'
    | '/api/admin/one-off-fix'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/toyyibpay-callback'
    | '/booking/return'
    | '/api/admin/one-off-fix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiToyyibpayCallbackRoute: typeof ApiToyyibpayCallbackRoute
  BookingReturnRoute: typeof BookingReturnRoute
  ApiAdminOneOffFixRoute: typeof ApiAdminOneOffFixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/toyyibpay-callback': {
      id: '/api/toyyibpay-callback'
      path: '/api/toyyibpay-callback'
      fullPath: '/api/toyyibpay-callback'
      preLoaderRoute: typeof ApiToyyibpayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/return': {
      id: '/booking/return'
      path: '/booking/return'
      fullPath: '/booking/return'
      preLoaderRoute: typeof BookingReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/one-off-fix': {
      id: '/api/admin/one-off-fix'
      path: '/api/admin/one-off-fix'
      fullPath: '/api/admin/one-off-fix'
      preLoaderRoute: typeof ApiAdminOneOffFixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiToyyibpayCallbackRoute: ApiToyyibpayCallbackRoute,
  BookingReturnRoute: BookingReturnRoute,
  ApiAdminOneOffFixRoute: ApiAdminOneOffFixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
